// Copyright 2025-2026 Neil Henderson
//
//! The `ast_unique_name` module defines the [AstUniqueName] type.

use std::fmt;

/// A unique string name for a variable, function, or type alias identifier.
///
/// Unique names are generated by the [IdentifierResolver](super::super::identifier_resolution::IdentifierResolver).
/// In some cases an identifier keeps its declared name (e.g. external variables or functions).
#[derive(Debug, Clone, Eq, PartialEq, Hash)]
pub struct AstUniqueName(String);

impl PartialEq<&str> for AstUniqueName {
    fn eq(&self, other: &&str) -> bool {
        self.0 == *other
    }
}

impl AsRef<AstUniqueName> for AstUniqueName {
    fn as_ref(&self) -> &AstUniqueName {
        self
    }
}

impl fmt::Display for AstUniqueName {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

impl AstUniqueName {
    /// Creates an `AstUniqueName` from a string that must be already unique.
    pub fn new<S: Into<String>>(s: S) -> Self {
        Self(s.into())
    }

    /// Returns `true` if the unique name string has a length of zero, and `false` otherwise.
    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }

    /// Returns the length of the unique name string, in bytes.
    pub fn len(&self) -> usize {
        self.0.len()
    }

    /// Returns the name as a string slice.
    pub fn as_str(&self) -> &str {
        &self.0
    }
}
